---
output: github_document
---

<!-- README.md is generated from README.Rmd. Please edit that file -->

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>",
  fig.path = "man/figures/README-",
  out.width = "100%"
)
```

# simplest_bayes

<!-- badges: start -->

<!-- badges: end -->


An attempt to make the relationships of Bayes' theorem graphically accessible and understandable at the simplest level

- **Language**: German, but its kinda not imprtant

### Quick Start

**Prerequisites**: R + RStudio installed

To get the app, copy the following code into your RStudio Console:

``` r
if (!require("devtools")) install.packages("devtools")
library(devtools)
devtools::install_github("gesagraf/simplest_bayes")
```

You also might need some additional packages:

``` r
if (!require("shiny")) install.packages("shiny")
if (!require("shinythemes")) install.packages("shinythemes")
if (!require("ggplot2")) install.packages("ggplot2")
if (!require("viridis")) install.packages("viridis")
```

Open file `app.R`. In the right corner of the skript pane there will be a Button `Run App`. Press it.


## Contributing

Feedback and contributions are welcome!

If you spot a typo, some incorrect content or see just a better way to do it, you
are welcome to collaborate. Either report it as an issue or even better, fix it
yourself!

Fork the repo, contribute and please submit your changes with a pull request. 


## Licensing

I would be happy to hear from you if you want to modify or redistribute the contents of this app. 

This software comes to you with an OpenSource license, because I am believer in the strength of commons.